# Generated by Django 4.2.11 on 2025-01-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=20)),
                ('starting', models.BooleanField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
