# Generated by Django 4.2.11 on 2025-01-20 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
        migrations.AddField(
            model_name='log',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 22, 3, 9, 231405)),
        ),
    ]
