# Generated by Django 4.2.11 on 2025-01-20 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_log_date_remove_log_time_log_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
